#!/usr/bin/env ruby

def exit_with_help_message
  puts <<EOS
I'd cheer for you, if only I knew who you are :(
Try again with `./cheers [Name] [MM/DD Birthday]
EOS
  exit
end

exit_with_help_message if ARGV.empty?

original_name = ARGV[0]
cheerable_name = original_name.upcase.gsub(/[^A-Z]/, "")

exit_with_help_message if cheerable_name.empty?

cheerable_name.each_char do |char|
  article = "n" if "AEFHILMNORSX".include? char
  puts "Give me a#{article}... #{char}"
end
puts "#{original_name}’s just GRAND!"
puts ""
puts "I would wish you a Happy Birthday if I knew when that is."



